### ISSUE TITLE
Not finding Printers

### ISSUE THREAD

**Issue by Gregorylibiny** [Zebra/Zebra-Printer-Samples#12]
I haven't been able to get the demo app to find my printer. 
Our printer is Zebra ZD421, and the device I'm using is a Zebra TC26 running Android 11.
Any ideas?

**Comment by ssizebra** [comment]
Do you mean that your app on TC26 (Android 11) cannot find printers over Bluetooth?

**Comment by Gregorylibiny** [comment]
Correct

**Comment by ssizebra** [comment]
There are two things to look at:
1. The app must have the ACCESS_FINE_LOCATION in the manifest file and must to request for the "location permission" explicitly from the user. See this article for detail - [Link-OS SDK for Android | Permissions and Bluetooth API](https://developer.zebra.com/blog/link-os-sdk-android-permissions-and-bluetooth-api)
2. Make sure if your ZD421 printer has Bluetooth, Bluetooth Low Energy or both. They must be enabled. You can use the Printer Setup app (Android or iOS) to configure Bluetooth settings on the ZD421. Not every ZD421 printer has Bluetooth. By default, Bluetooth is disabled in the factory setting.

**Comment by Gregorylibiny** [comment]
I have included ACCESS_FINE_LOCATION location in the manifest file and enabled the permission for it.
I've enabled the printer for Bluetooth through the printer setup app, the printer has LE Bluetooth.

**Comment by ssizebra** [comment]
To discovery BTLE, you need to use the [Link-OS Multiplatform SDK for Android BTLE](https://www.zebra.com/us/en/support-downloads/printer-software/link-os-multiplatform-sdk.html), which has the [BluetoothLeDiscoverer](https://techdocs.zebra.com/link-os/2-14/android_btle/content/com/zebra/sdk/btlecomm/bluetoothlediscoverer).

**Comment by Gregorylibiny** [comment]
I believe that is the one I installed, I was following this guide [https://developer.zebra.com/blog/develop-react-native-printing-app-android-ios-link-os-sdk](url)
The issue I ran into is I wasn't using the BTLE library, I appreciate the help in solving this!
